steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-west2-docker.pkg.dev/$PROJECT_ID/htt4ps-energy-checker-docker-repo/http4s-energy-checker-image:tag1', '.' ]
images:
  - 'us-west2-docker.pkg.dev/$PROJECT_ID/htt4ps-energy-checker-docker-repo/http4s-energy-checker-image:tag1'